# libraries

library(targets)
library(tidyverse)
library(janitor)
library(vegan)
library(ggvegan)
library(traitstrap)
library(dataDocumentation)
library(dataDownloader)
library(broom)
library(broom.mixed)
library(glue)
library(geodata)
library(terra)