# Load libraries
library(tidyverse)
library(vegan)
library(ggvegan)
library(traitstrap)
library(dataDocumentation)
library(readxl)
library(broom)
library(broom.mixed)
library(glue)
library(geodata)
library(terra)
library(MetBrewer)
library(maps)
library(performance)
library(see)
library(lme4)
library(lmerTest)
